Check for set -o pipefail
Like the other set lint checks, this will hopefully catch errors
in element scripts sooner.

Change-Id: Ib1600938f6ffed657ff2950ef54bbcbdb5a0db08

diff --git a/bin/dib-lint b/bin/dib-lint
--- a/bin/dib-lint
+++ b/bin/dib-lint
@@ -72,7 +72,7 @@ for i in $(find elements -type f); do
         fi
     fi
 
-    # Check that all scripts are set -eu
+    # Check that all scripts are set -eu -o pipefail
     # NOTE(bnemec): This doesn't verify that the set call occurs high
     # enough in the file to be useful, but hopefully nobody will be
     # sticking set calls at the end of their file to trick us.  And if
@@ -91,6 +91,12 @@ for i in $(find elements -type f); do
         if ! excluded setu; then
             if [ -z "$(grep "^set -[^ ]*u" $i)" ]; then
                 echo "ERROR: $i is not set -u"
+                rc=1
+            fi
+        fi
+        if ! excluded setpipefail; then
+            if [ -z "$(grep "^set -o pipefail" $i)" ]; then
+                echo "ERROR: $i is not set -o pipefail"
                 rc=1
             fi
         fi
