Stop apt-get installing qemu-img.
This is simply a prerequisite and we should not try to
apt-get install it inline.

Remove this code and exit with an error if qemu-img is
not found.

Change-Id: I52d47a95d24d4bfe801ba664200604bd385dc67f

diff --git a/lib/img-functions b/lib/img-functions
--- a/lib/img-functions
+++ b/lib/img-functions
@@ -41,8 +41,9 @@ function cleanup () {
 function ensure_nbd () {
     NBD=`which qemu-nbd` || true
     if [ -z "$NBD" ];  then
-        echo "Need qemu-nbd to build qcow2 files."
-	sudo apt-get install qemu-utils
+        echo "qemu-nbd is not found in your PATH"
+        echo "Please install it on your system"
+        exit 1
     fi
     # prep nbd for mounting
     (lsmod | grep '^nbd ') || sudo modprobe nbd max_part=16
